version: "3.7"
services:
    mysql:
      container_name: MysqlDocker
      image: mysql
      ports:
          - 33060:3306
      command: --default-authentication-plugin=mysql_native_password
      
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: db_mysql_inmunobio         
      volumes:
          - ../data/mysql:/var/lib/mysql
      cap_add:
          - SYS_NICE
      networks:
          - env_prod
          
    mongo:
      container_name: MongoDocker
      restart: always
      image: mongo:4.4.6
      ports:
          - 27017:27017
      volumes:
        - ../data/mongo:/data/db
      networks:
          - env_prod

    flask:
      container_name: BackDocker
      restart: always
      build:
        context: ./
      ports: 
         - 8080:8080
      links:
         - mysql
         - mongo
      networks:
         - env_prod
      volumes:
        - ../data/uploads
      depends_on:
         - mongo
         - mysql

networks:
  env_prod:
    driver: bridge  
    #activate ipv6
    driver_opts: 
            com.docker.network.enable_ipv6: "true"
    #IP Adress Manager
    # ipam: 
    #     driver: default
    #     config:
    #     - subnet: 172.16.232.0/24
    #       gateway: 172.16.232.1
    #     - subnet: "2001:3974:3979::/64"
    #       gateway: "2001:3974:3979::1"
#   env_prep:   
#     driver: bridge  
#     #activate ipv6
#     driver_opts: 
#             com.docker.network.enable_ipv6: "true"
#     #IP Adress Manager
#     ipam:
#         driver: default
#         config:
#         - subnet: 172.16.235.0/24
#           gateway: 172.16.235.1
#         - subnet: "2001:3984:3989::/64"
#           gateway: "2001:3984:3989::1"